# Generated by Django 4.0 on 2021-12-15 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('host', models.TextField()),
                ('participant_details_list', models.TextField()),
                ('giving_list', models.TextField(blank=True, null=True)),
                ('num_participants', models.IntegerField()),
                ('names_drawn', models.BooleanField(default=False)),
                ('emails_sent', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
